### ISSUE TITLE
Build Login Component and (Mock) Auth Service

### ISSUE THREAD

**Issue by AdamDKing** [revaturelabs/screening-ui#59]
Create the component for a login page -- taking form input user and pass.  Inject auth service as dependency.

Create the Auth service!  It should have a way to check credentials, check login status, and check admin status.  This should all be mocked up since there's no connection yet.

**Comment by JakenPrime** [comment]
login in component was created, authentication service created and stores login in information in local storage, alert service updated with new alerts for bad login in attempts.
