### ISSUE TITLE
Read + Writeup Mock Report Contents

### ISSUE THREAD

**Issue by AdamDKing** [revaturelabs/screening-ui#61]
The charts/frontend work off of mock reports.  Check out those reports, figure out their format, and then write that format up to make development easier.  When I say "format" I mean the names of parameters, what's an object, what's a string, what's an array, etc.  This shouldn't be hard, so if you're having trouble ask questions.

**Comment by AdamDKing** [comment]
screening-ui/src/app/mock-data/mock-reports.ts

Make sure you're on branch 1902-Mehrab

Maybe checkout mock-emails as well, though not if it's a pain

**Comment by johnmasiello** [comment]
Hi, this email was sent to me in error. Maybe the intended recipient was
John De Jesus?

Best of luck,
John Masiello

**Comment by AdamDKing** [comment]
*** NOT ISSUE RELATED, ATTN PRIOR BATCHES ***

Hi!

If you're from a prior batch, you may have subscribed yourself to this project.  That means you'll get automated notification emails based on your own settings.  Most likely you signed up to watch the project and never stopped watching it.

You'll know when you get an automated notification email because the email will be from the address "notifications@github.com" and in the body of the email you'll see the line "You are receiving this because you are subscribed to this thread".  Those two things indicate the email is an automated notification email from GitHub, that you're receiving the email because you're subscribed to the thread. 
 Also included in these emails is the option to mute the thread, if you so desire.  Please DON'T RESPOND to these emails, as that will automatically make a comment and clutter up the issue tracker.

Do feel free to listen in as we work, if you like.

Cheers,

Adam

**Comment by AdamDKing** [comment]
Check the docs folder for these files.  Issue closed.
