### ISSUE TITLE
Frontend/Backend basic authentication

### ISSUE THREAD

**Issue by AdamDKing** [revaturelabs/screening-ui#63]
Frontend:
Refactor the Auth Service to actually send username and password and receive a role back.

Figure out two things from backend: WHAT DO I SEND? and WHAT DO I GET?

Backend:
Build something in Java that does basic auth.  Should take in HTTP POST requests and respond by providing that user's role.  This can interface with spring security, or cognito, or neither, or both. (ask Jonathan or Brandon for guidance)

**Comment by Tubocass** [comment]
Right now, Email and Password are sent to AWS, which stores the User Pool. The User Pool is linked to IAM security and provides access to other AWS tools, and also gives us JSON Web Tokens (JWTs).

These JWTs are sent in the header of Http requests to the server, where they can be used for Authenticated Access to our micro-services.

On the Java side, we still need to deserialize and make use of the tokens.
